project_id = "xoirisnxbtguzbearhft"

[functions.ai-chat]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.lookup-result]
verify_jwt = false

[functions.admin-auth-captcha]
verify_jwt = false